import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import Logo, { LOGOS } from './Logo';
import { sys } from '../foundations/tokens';

// ═══════════════════════════════════════════
//  Logo — Figma's `logos-and-graphics` page, 109 marks served as files.
//  The manifest is generated by listing the directory, so nothing here can
//  claim a file that is not on disk.
// ═══════════════════════════════════════════

const meta: Meta<typeof Logo> = {
  title: 'Components/Display/Logo',
  component: Logo,
  parameters: { layout: 'padded' },
};
export default meta;

const sans = "'Graphik TH', sans-serif";
const mono = 'ui-monospace, SFMono-Regular, Menlo, monospace';

const GROUP_LABEL: Record<string, string> = {
  bank: 'ธนาคาร',
  brand: 'แบรนด์',
  'social-icon': 'โซเชียล (32px, มี hover)',
  'quick-menu': 'Quick menu',
  'tab-menu': 'Tab menu',
  'nav-menu': 'Nav menu',
  jidrit: 'จิ๊ดริด',
  gift: 'ของขวัญ',
  graphic: 'กราฟิกอื่น',
  other: 'อื่นๆ',
};

const Tile: React.FC<{ entry: (typeof LOGOS)[number] }> = ({ entry }) => (
  <div style={{ width: 108, textAlign: 'center' }}>
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: 96,
        borderRadius: sys('radius-lg'),
        background: sys('color-background-default'),
        border: `1px solid ${sys('color-border-accent-gray-soft-light')}`,
      }}
    >
      <Logo name={entry.name} alt="" size={entry.group === 'social-icon' ? 32 : 64} />
    </div>
    <div
      style={{
        fontSize: 9.5,
        fontFamily: mono,
        color: sys('color-text-tertiary-default'),
        marginTop: 6,
        lineHeight: 1.4,
        wordBreak: 'break-all',
      }}
    >
      {entry.name}
    </div>
    <div style={{ fontSize: 9, fontFamily: mono, color: sys('color-text-state-light-gray') }}>
      {entry.format} · {Math.round(entry.bytes / 1024)}KB
    </div>
  </div>
);

export const Gallery: StoryObj = {
  name: 'All marks',
  render: () => {
    const groups = [...new Set(LOGOS.map((l) => l.group))];
    const total = LOGOS.reduce((a, l) => a + l.bytes, 0);
    return (
      <div style={{ fontFamily: sans, maxWidth: 1000 }}>
        <h2 style={{ fontSize: 20, margin: '0 0 6px' }}>logos-and-graphics</h2>
        <p style={{ margin: '0 0 8px', fontSize: 13, lineHeight: 1.75, color: sys('color-text-tertiary-default'), maxWidth: 660 }}>
          {LOGOS.length} มาร์ค · {Math.round(total / 1024)}KB บนดิสก์ · <strong>ไม่เข้า bundle</strong> —
          เสิร์ฟเป็นไฟล์ผ่าน <code style={{ fontFamily: mono }}>staticDirs</code>
        </p>
        <p
          style={{
            margin: '0 0 28px',
            padding: '10px 14px',
            maxWidth: 660,
            fontSize: 12.5,
            lineHeight: 1.8,
            borderLeft: `3px solid ${sys('color-border-accent-gray-light')}`,
            background: sys('color-background-light'),
            color: sys('color-text-secondary-default'),
          }}
        >
          <strong>เปลี่ยนสีไม่ได้ และตั้งใจให้เปลี่ยนไม่ได้</strong> — 70 จาก 107 ตัวมีสีตายตัวไม่ผูก
          variable (รวม 229 สีทั้งหน้า) และหลายตัวเป็นโลโก้ของคนอื่น เรนเดอร์เป็น{' '}
          <code style={{ fontFamily: mono }}>&lt;img&gt;</code> ซึ่งไม่มี prop สี — กันพลาดด้วยโครงสร้าง
          ไม่ใช่ด้วยกฎที่ต้องจำ
        </p>

        {groups.map((g) => {
          const items = LOGOS.filter((l) => l.group === g);
          return (
            <div key={g} style={{ marginBottom: 34 }}>
              <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 12 }}>
                {GROUP_LABEL[g] ?? g}{' '}
                <span style={{ fontFamily: mono, fontSize: 11, color: sys('color-text-tertiary-default') }}>
                  {items.length}
                </span>
              </div>
              <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
                {items.map((e) => (
                  <Tile key={e.name} entry={e} />
                ))}
              </div>
            </div>
          );
        })}
      </div>
    );
  },
};

export const WhyFiles: StoryObj = {
  name: '🔍 ทำไมไม่เอาเข้า icon set',
  render: () => {
    const th: React.CSSProperties = {
      textAlign: 'left',
      padding: '7px 12px',
      fontSize: 11,
      fontWeight: 600,
      color: sys('color-text-tertiary-default'),
      borderBottom: `2px solid ${sys('color-border-accent-gray-soft-light')}`,
    };
    const td: React.CSSProperties = {
      padding: '7px 12px',
      borderBottom: `1px solid ${sys('color-background-light')}`,
      fontSize: 12.5,
    };
    const svg = LOGOS.filter((l) => l.format === 'svg');
    const png = LOGOS.filter((l) => l.format === 'png');
    return (
      <div style={{ fontFamily: sans, maxWidth: 760, lineHeight: 1.75 }}>
        <h2 style={{ fontSize: 20, margin: '0 0 18px' }}>มาร์ค ≠ ไอคอน</h2>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 30 }}>
          <thead>
            <tr>
              <th style={th} />
              <th style={th}>icon</th>
              <th style={th}>logo / graphic</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['สี', 'สีเดียว รับ currentColor', '229 สีตายตัวทั้งหน้า'],
              ['เปลี่ยนสี', 'ต้องได้', 'ห้าม — โลโก้ธนาคารเป็นของเขา'],
              ['ขนาด', '10 ขั้น 12–72', '80 ตายตัว (โซเชียล 32)'],
              ['ผูก token', 'ใช่', '70 จาก 107 ไม่ผูกเลย'],
              ['เก็บที่', 'icon-data.ts (bundle)', 'assets/logos (ไฟล์)'],
            ].map(([a, b, c]) => (
              <tr key={a}>
                <td style={{ ...td, fontWeight: 600, width: 110 }}>{a}</td>
                <td style={{ ...td, color: sys('color-text-tertiary-default') }}>{b}</td>
                <td style={td}>{c}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <h3 style={{ fontSize: 15, margin: '0 0 8px' }}>ฟอร์แมตตัดสินด้วยการวัด</h3>
        <p style={{ margin: '0 0 12px', fontSize: 13, color: sys('color-text-secondary-default') }}>
          export SVG ก่อน ถ้า ≤20KB ใช้ SVG ถ้าเกินให้ลอง PNG@3x แล้วเอาตัวที่เล็กกว่า —
          ตัวหนักสุด <code style={{ fontFamily: mono }}>gp-jidrit-search</code> จาก{' '}
          <strong>412KB เหลือ 26KB</strong> เล็กลง 16 เท่า
        </p>
        <div style={{ fontFamily: mono, fontSize: 12, marginBottom: 26 }}>
          svg {svg.length} ตัว · {Math.round(svg.reduce((a, l) => a + l.bytes, 0) / 1024)}KB
          <br />
          png {png.length} ตัว · {Math.round(png.reduce((a, l) => a + l.bytes, 0) / 1024)}KB
        </div>

        <h3 style={{ fontSize: 15, margin: '0 0 8px' }}>ยังไม่ได้เอาเข้า</h3>
        <p style={{ margin: 0, fontSize: 13, color: sys('color-text-secondary-default') }}>
          <code style={{ fontFamily: mono }}>noti-error</code> กับ{' '}
          <code style={{ fontFamily: mono }}>Card</code> อยู่หน้าเดียวกันแต่ไม่ใช่มาร์ค 80×80 —
          ตัวหนึ่งเป็นชุดภาพประกอบ อีกตัวเป็นกราฟิกการ์ด ต้องตัดสินแยกก่อนว่าจะเก็บยังไง
        </p>
      </div>
    );
  },
};
