// ===================================================================
// metadata.generated.ts — GENERATED FILE, DO NOT EDIT BY HAND
// Regenerate: python3 tools/gen-metadata-map.py
//
// Story title -> the manifest that governs it, joined by story-file stem. The
// panel in .storybook/preview.ts reads this so a reader can see the contract
// (scope, public, level) beside the component instead of in a file they would
// have to clone the repo to open.
// ===================================================================

export interface ComponentMeta {
  name: string;
  type: string;
  responsibility: string;
  composition_level: string | null;
  dependencies: string[];
  slots: unknown[];
  pattern: string | null;
  organisms: string[];
  scope: string;
  project: string | null;
  feature: string | null;
  public: boolean;
  folder: string;
}

export const METADATA: Record<string, ComponentMeta> = {
  "Components/Commerce/LottoBoard/MainHomeCard": {"name": "lotto-board", "type": "component", "responsibility": "Pick lottery numbers from a dense grid", "composition_level": "organism", "dependencies": ["button", "text-field", "dropdown"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/lotto-board"},
  "Components/Display/Avatar": {"name": "avatar", "type": "component", "responsibility": "Show who someone is at a glance", "composition_level": "atom", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/avatar"},
  "Components/Display/Divider": {"name": "divider", "type": "component", "responsibility": "Separate content without introducing a new surface", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/divider"},
  "Components/Display/Icon": {"name": "icon", "type": "component", "responsibility": "Render a single pictogram", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/icon"},
  "Components/Display/Logo": {"name": "logo", "type": "component", "responsibility": "Show a brand mark or graphic that must not be recoloured", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/logo"},
  "Components/Display/LotteryCard": {"name": "card", "type": "component", "responsibility": "Show a lottery card face with its id", "composition_level": "atom", "dependencies": ["logo"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/card"},
  "Components/Display/TitleWithUnderline": {"name": "title-with-underline", "type": "component", "responsibility": "Head a section with the brand underline treatment", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/title-with-underline"},
  "Components/Feedback/Alert": {"name": "alert", "type": "component", "responsibility": "Warn inline without interrupting", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/alert"},
  "Components/Feedback/CountdownTimer": {"name": "countdown-timer", "type": "component", "responsibility": "Count a reservation down to its deadline", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/countdown-timer"},
  "Components/Feedback/ErrorState": {"name": "error-state", "type": "component", "responsibility": "Explain why a screen has nothing to show, and offer the way out", "composition_level": "organism", "dependencies": ["logo", "action-bar"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/error-state"},
  "Components/Feedback/Loading": {"name": "loading", "type": "component", "responsibility": "Signal that work is in progress", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/loading"},
  "Components/Feedback/ProgressBar": {"name": "progress-bars", "type": "component", "responsibility": "Show how far along a task is", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/progress-bars"},
  "Components/Feedback/Skeleton": {"name": "skeleton", "type": "component", "responsibility": "Hold a place while content loads", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/skeleton"},
  "Components/Feedback/Toast": {"name": "toast", "type": "component", "responsibility": "Report the outcome of an action without blocking", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/toast"},
  "Components/Feedback/Tooltip": {"name": "tooltip", "type": "component", "responsibility": "Explain an element on hover or focus, without taking focus itself", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/tooltip"},
  "Components/Forms/Button": {"name": "button", "type": "component", "responsibility": "Trigger a single action", "composition_level": "atom", "dependencies": ["icon", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/button"},
  "Components/Forms/Checkbox": {"name": "checkbox", "type": "component", "responsibility": "Toggle one option on or off", "composition_level": "atom", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/checkbox"},
  "Components/Forms/Dropdown": {"name": "dropdown", "type": "component", "responsibility": "Pick one option from a list", "composition_level": "molecule", "dependencies": ["input", "icon", "list-item"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/dropdown"},
  "Components/Forms/ImageUpload": {"name": "image-upload", "type": "component", "responsibility": "Take an image from the user and show what they picked", "composition_level": "molecule", "dependencies": ["icon", "button", "loading"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/image-upload"},
  "Components/Forms/RadioButton": {"name": "radio-buttons", "type": "component", "responsibility": "Pick exactly one option from a small set", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/radio-buttons"},
  "Components/Forms/TextField": {"name": "text-field", "type": "component", "responsibility": "Accept a line of typed input", "composition_level": "atom", "dependencies": ["label", "icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/text-field"},
  "Components/Forms/ToggleSwitch": {"name": "toggle-switch", "type": "component", "responsibility": "Switch a setting between two states", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/toggle-switch"},
  "Components/Layout/ActionBar": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Layout/Footer": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Layout/Header": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Layout/Header/HeaderCounter": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Layout/ProfileHeader": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Layout/ProfileSummary": {"name": "top-and-footer", "type": "component", "responsibility": "Frame every page with a header and footer", "composition_level": "organism", "dependencies": ["navigation-bar", "icon", "button"], "slots": [], "pattern": null, "organisms": [], "scope": "project", "project": "lotteryplus", "feature": null, "public": false, "folder": "projects/lotteryplus/shared/components/top-and-footer"},
  "Components/Navigation/Breadcrumb": {"name": "breadcrumb", "type": "component", "responsibility": "Show the path back through a page hierarchy", "composition_level": "molecule", "dependencies": ["link", "icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/breadcrumb"},
  "Components/Navigation/NavigationBar": {"name": "navigation-bar", "type": "component", "responsibility": "Move between the top-level areas of the app", "composition_level": "organism", "dependencies": ["icon", "link"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/navigation-bar"},
  "Components/Navigation/Tabs": {"name": "tabs", "type": "component", "responsibility": "Switch between sibling views in place", "composition_level": "organism", "dependencies": ["tab-item"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/tabs"},
  "Components/Overlay/Accordion": {"name": "accordion", "type": "component", "responsibility": "Reveal and hide a block of content on demand", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/accordion"},
  "Components/Overlay/BottomSheet": {"name": "bottom-sheet", "type": "component", "responsibility": "Raise a panel from the bottom edge on mobile", "composition_level": "organism", "dependencies": ["overlay"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/bottom-sheet"},
  "Components/Overlay/Modal": {"name": "modal", "type": "component", "responsibility": "Interrupt the flow for a decision that cannot wait", "composition_level": "organism", "dependencies": ["button", "icon", "overlay"], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/components/modal"},
  "Features/Home/Components/AddOnServiceCard": {"name": "add-on-service-card", "type": "component", "responsibility": "แสดงบริการเสริมหนึ่งรายการพร้อมปุ่มเข้าใช้", "composition_level": "molecule", "dependencies": ["button", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/add-on-service-card"},
  "Features/Home/Components/CarouselDots": {"name": "carousel-dots", "type": "component", "responsibility": "บอกว่ากำลังอยู่หน้าที่เท่าไหร่ของแถบเลื่อน", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/carousel-dots"},
  "Features/Home/Components/CountdownPanel": {"name": "countdown-panel", "type": "component", "responsibility": "นับเวลาถอยหลังจนถึงเวลาปิดรอบ", "composition_level": "molecule", "dependencies": ["text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/countdown-panel"},
  "Features/Home/Components/FlashSaleBanner": {"name": "flash-sale-banner", "type": "component", "responsibility": "ประกาศรอบขายพิเศษพร้อมเวลาที่เหลือ", "composition_level": "molecule", "dependencies": ["CountdownPanel", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/flash-sale-banner"},
  "Features/Home/Components/HomeAdsRow": {"name": "home-ads-row", "type": "component", "responsibility": "วางแบนเนอร์โฆษณาเรียงเป็นแถวบนหน้าแรก", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/home-ads-row"},
  "Features/Home/Components/HomeRedBlock": {"name": "home-red-block", "type": "component", "responsibility": "พื้นแดงที่รองส่วนสลากของหน้าแรก", "composition_level": "atom", "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/home-red-block"},
  "Features/Home/Components/LotterySection": {"name": "lottery-section", "type": "component", "responsibility": "จัดกลุ่มสลากหนึ่งหมวดพร้อมหัวข้อและปุ่มดูทั้งหมด", "composition_level": "molecule", "dependencies": ["LotteryTile", "button", "icon", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/lottery-section"},
  "Features/Home/Components/LotteryTile": {"name": "lottery-tile", "type": "component", "responsibility": "แสดงสลากหนึ่งใบให้หยิบใส่ตะกร้าได้", "composition_level": "molecule", "dependencies": ["icon"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/lottery-tile"},
  "Features/Home/Components/PromoBanner": {"name": "promo-banner", "type": "component", "responsibility": "แสดงแบนเนอร์โปรโมชันหนึ่งชิ้น", "composition_level": "molecule", "dependencies": ["CarouselDots"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/promo-banner"},
  "Features/Home/Components/QuickMenuGrid": {"name": "quick-menu-grid", "type": "component", "responsibility": "ทางเข้าบริการหลักเรียงเป็นตาราง", "composition_level": "molecule", "dependencies": ["CarouselDots", "logo", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/quick-menu-grid"},
  "Features/Home/Components/SeoPanel": {"name": "seo-panel", "type": "component", "responsibility": "บล็อกข้อความอธิบายบริการท้ายหน้าแรก", "composition_level": "molecule", "dependencies": ["icon", "text"], "slots": [], "pattern": null, "organisms": [], "scope": "feature", "project": "lotteryplus", "feature": "home", "public": false, "folder": "projects/lotteryplus/features/home/components/seo-panel"},
  "Helpers/InfiniteScroll": {"name": "infinity-scroll", "type": "helper", "responsibility": "Load the next page when the end scrolls into view", "composition_level": null, "dependencies": [], "slots": [], "pattern": null, "organisms": [], "scope": "global", "project": null, "feature": null, "public": true, "folder": "global/helpers/infinity-scroll"},
};

export const metaFor = (title: string): ComponentMeta | undefined =>
  METADATA[title];
