#!/usr/bin/env bash
# Split two days of work into reviewable commits, in dependency order.
#
#   bash tools/commit-plan.sh            # dry run — prints what each commit would take
#   bash tools/commit-plan.sh --run      # actually commits
#
# Nothing is pushed. Every commit is local and revertable with `git reset --soft HEAD~1`.
set -uo pipefail
cd "$(dirname "$0")/.."

RUN=0
[ "${1:-}" = "--run" ] && RUN=1

if [ "$RUN" = 1 ]; then
  branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "Refusing to commit straight onto '$branch'."
    echo "Make a branch first, e.g.:  git switch -c feat/design-system-p1"
    exit 1
  fi
fi

step() {
  local msg="$1"; shift
  echo
  echo "════════════════════════════════════════════"
  echo "  $msg"
  echo "════════════════════════════════════════════"
  local n=0
  for path in "$@"; do
    [ -e "$path" ] || { echo "  (skip, not present) $path"; continue; }
    if [ "$RUN" = 1 ]; then
      git add -- "$path"
    else
      git add --intent-to-add --dry-run -- "$path" >/dev/null 2>&1 || true
    fi
    local c
    # -uall, or an untracked directory counts as one path and the total lies.
    c=$(git status --porcelain -uall -- "$path" | wc -l | tr -d ' ')
    echo "  $path  ($c files)"
    n=$((n + c))
  done
  if [ "$RUN" = 1 ]; then
    if git diff --cached --quiet; then
      echo "  nothing staged — skipping commit"
    else
      git commit -q -m "$msg" && echo "  ✓ committed"
    fi
  else
    echo "  → would commit $n files"
  fi
}

echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
[ "$RUN" = 0 ] && echo "DRY RUN — nothing will be written. Re-run with --run to commit."

# ── 1. the pipeline first: everything downstream is generated by it
step "chore(tooling): token/component generators and the 8-step gate" \
  tools/ .storybook/

# ── 2. the source of truth the generators read, then what they emit
step "feat(tokens): design-library source of truth and generated token tiers" \
  design-library/ "ui/foundations/"

# icons are a registry the components import by name, so they land before the components
step "feat(icons): icon registry, deduplicated against Figma's own duplicate names" \
  "ui/icons/"

# ── 3. assets before the components that reference them
step "feat(assets): Graphik TH, brand marks and 112 Figma logos" \
  "ui/assets/" "ui/logos/"

# ── 4. the components themselves
step "feat(components): Header, Footer, ActionBar, Avatar, Divider, ErrorState, LotteryCard" \
  "ui/components/"

# ── 5. compositions on top of components
step "feat(patterns): AppShell and BareScreen, plus the component inventory story" \
  "ui/patterns/" "ui/system/" "ui/pages/"

# ── 6. project memory last — it describes everything above
step "docs: project spec, memory and the Phase 2 rename table" \
  spec.md MEMORY.md docs/ PRD-lottery-reservation.md

echo
echo "════════════════════════════════════════════"
echo "  Left out on purpose"
echo "════════════════════════════════════════════"
cat <<'NOTE'
  lotteryplus-frontend-main/   52MB, 2537 files — another team's repo, vendored for
                               reference. Committing it would fork it silently and go
                               stale. Recommend adding to .gitignore instead.
  slide/  wireframe/           2.1MB of decks and one wireframe — unrelated to the
                               library. Commit separately if they belong here at all.

  Neither is staged by this script. Decide, then either gitignore or commit by hand.
NOTE
echo
echo "════════════════════════════════════════════"
echo "  Coverage check"
echo "════════════════════════════════════════════"
# Listing directories by hand is how `ui/icons` was missed the first time:
# six commits went in and the icon registry stayed behind, so HEAD referenced icons
# it did not contain. This asks git what is left instead of trusting the list above.
missed=$(git status --porcelain -uall \
  | grep -vE '^.. "?(lotteryplus-frontend-main|slide|wireframe)/' \
  | grep -vE '\.DS_Store' || true)
if [ -n "$missed" ]; then
  echo "  ✗ still uncommitted inside the library — add these paths to a step above:"
  printf '%s\n' "$missed" | sed 's/^/      /'
else
  echo "  ✓ nothing left inside the library"
fi

echo
echo "  Untracked and deliberately skipped:"
git status --porcelain -uall | sed 's/^/  /' | head -6
echo "  ... $(git status --porcelain -uall | wc -l | tr -d ' ') files still unstaged"
